// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXsr0DeK6fkmXK7eFdjfuz86cjzvjPhI',
    appId: '1:493935451188:web:3f15dfd72a7aa74f587e61',
    messagingSenderId: '493935451188',
    projectId: 'beatjerky-68aaa',
    authDomain: 'beatjerky-68aaa.firebaseapp.com',
    databaseURL: 'https://beatjerky-68aaa-default-rtdb.firebaseio.com',
    storageBucket: 'beatjerky-68aaa.firebasestorage.app',
    measurementId: 'G-WKEF7B254R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4UMyxCSr-HQB8wTC3BZjedEvEimrBgjs',
    appId: '1:493935451188:android:6ac4d1b1e5310913587e61',
    messagingSenderId: '493935451188',
    projectId: 'beatjerky-68aaa',
    databaseURL: 'https://beatjerky-68aaa-default-rtdb.firebaseio.com',
    storageBucket: 'beatjerky-68aaa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuXsr0DeK6fkmXK7eFdjfuz86cjzvjPhI',
    appId: '1:493935451188:web:509647ef979a063e587e61',
    messagingSenderId: '493935451188',
    projectId: 'beatjerky-68aaa',
    authDomain: 'beatjerky-68aaa.firebaseapp.com',
    databaseURL: 'https://beatjerky-68aaa-default-rtdb.firebaseio.com',
    storageBucket: 'beatjerky-68aaa.firebasestorage.app',
    measurementId: 'G-HM8C1HTXZJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzg5zxOAZ8SruSIjWFRA6nIGbFtku9p48',
    appId: '1:493935451188:ios:03d0aae8c0959cc1587e61',
    messagingSenderId: '493935451188',
    projectId: 'beatjerky-68aaa',
    databaseURL: 'https://beatjerky-68aaa-default-rtdb.firebaseio.com',
    storageBucket: 'beatjerky-68aaa.firebasestorage.app',
    iosBundleId: 'com.beatjerky.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzg5zxOAZ8SruSIjWFRA6nIGbFtku9p48',
    appId: '1:493935451188:ios:a1563adeb0224cdb587e61',
    messagingSenderId: '493935451188',
    projectId: 'beatjerky-68aaa',
    databaseURL: 'https://beatjerky-68aaa-default-rtdb.firebaseio.com',
    storageBucket: 'beatjerky-68aaa.firebasestorage.app',
    iosBundleId: 'com.beatjerky.app',
  );

}